import type { Ingredient, Recipe } from '@/types';

/**
 * The bundled recipe library and the pantry vocabulary it is written against.
 *
 * Pure data, split from the scoring logic in `recipes.ts` so neither file grows
 * unwieldy. Every id in a recipe's `ingredients` must exist in `INGREDIENTS` —
 * `assertRecipeData()` in `recipes.ts` checks this in development.
 *
 * The library is deliberately biased toward high-protein, moderate-calorie
 * cooking, because that is what the app's adaptive plan asks cutters to eat.
 * Seasonings and assumed staples (salt, pepper, stock, vinegar) belong in a
 * recipe's `extras`, not here — they should never filter a recipe out.
 */

export const INGREDIENTS: Ingredient[] = [
  // Protein
  { id: 'egg', label: 'Eggs', group: 'protein' },
  { id: 'chicken', label: 'Chicken', group: 'protein' },
  { id: 'turkey', label: 'Turkey', group: 'protein' },
  { id: 'beef', label: 'Beef mince', group: 'protein' },
  { id: 'pork', label: 'Pork', group: 'protein' },
  { id: 'salmon', label: 'Salmon', group: 'protein' },
  { id: 'tuna', label: 'Tuna', group: 'protein' },
  { id: 'cod', label: 'White fish', group: 'protein' },
  { id: 'shrimp', label: 'Prawns', group: 'protein' },
  { id: 'tofu', label: 'Tofu', group: 'protein' },
  { id: 'tempeh', label: 'Tempeh', group: 'protein' },
  { id: 'whey', label: 'Protein powder', group: 'protein' },
  { id: 'sardines', label: 'Sardines', group: 'protein' },
  { id: 'edamame', label: 'Edamame', group: 'protein' },
  { id: 'lamb', label: 'Lamb', group: 'protein' },

  // Carbs
  { id: 'oats', label: 'Oats', group: 'carbs' },
  { id: 'rice', label: 'Rice', group: 'carbs' },
  { id: 'pasta', label: 'Pasta', group: 'carbs' },
  { id: 'bread', label: 'Bread', group: 'carbs' },
  { id: 'tortilla', label: 'Tortillas', group: 'carbs' },
  { id: 'potato', label: 'Potatoes', group: 'carbs' },
  { id: 'sweet-potato', label: 'Sweet potato', group: 'carbs' },
  { id: 'quinoa', label: 'Quinoa', group: 'carbs' },
  { id: 'lentils', label: 'Lentils', group: 'carbs' },
  { id: 'chickpeas', label: 'Chickpeas', group: 'carbs' },
  { id: 'beans', label: 'Black beans', group: 'carbs' },
  { id: 'couscous', label: 'Couscous', group: 'carbs' },
  { id: 'noodles', label: 'Noodles', group: 'carbs' },
  { id: 'pitta', label: 'Pitta bread', group: 'carbs' },

  // Produce
  { id: 'spinach', label: 'Spinach', group: 'veg' },
  { id: 'broccoli', label: 'Broccoli', group: 'veg' },
  { id: 'salad', label: 'Salad leaves', group: 'veg' },
  { id: 'tomato', label: 'Tomatoes', group: 'veg' },
  { id: 'cucumber', label: 'Cucumber', group: 'veg' },
  { id: 'pepper', label: 'Peppers', group: 'veg' },
  { id: 'onion', label: 'Onion', group: 'veg' },
  { id: 'garlic', label: 'Garlic', group: 'veg' },
  { id: 'mushroom', label: 'Mushrooms', group: 'veg' },
  { id: 'courgette', label: 'Courgette', group: 'veg' },
  { id: 'avocado', label: 'Avocado', group: 'veg' },
  { id: 'berries', label: 'Berries', group: 'veg' },
  { id: 'banana', label: 'Banana', group: 'veg' },
  { id: 'lemon', label: 'Lemon', group: 'veg' },
  { id: 'carrot', label: 'Carrots', group: 'veg' },
  { id: 'green-beans', label: 'Green beans', group: 'veg' },
  { id: 'cauliflower', label: 'Cauliflower', group: 'veg' },
  { id: 'kale', label: 'Kale', group: 'veg' },
  { id: 'peas', label: 'Peas', group: 'veg' },
  { id: 'sweetcorn', label: 'Sweetcorn', group: 'veg' },
  { id: 'aubergine', label: 'Aubergine', group: 'veg' },
  { id: 'butternut', label: 'Butternut squash', group: 'veg' },
  { id: 'cabbage', label: 'Cabbage', group: 'veg' },
  { id: 'apple', label: 'Apple', group: 'veg' },
  { id: 'orange', label: 'Orange', group: 'veg' },
  { id: 'mango', label: 'Mango', group: 'veg' },

  // Dairy
  { id: 'greek-yogurt', label: 'Greek yogurt', group: 'dairy' },
  { id: 'cottage-cheese', label: 'Cottage cheese', group: 'dairy' },
  { id: 'milk', label: 'Milk', group: 'dairy' },
  { id: 'cheese', label: 'Cheese', group: 'dairy' },
  { id: 'feta', label: 'Feta', group: 'dairy' },
  { id: 'mozzarella', label: 'Mozzarella', group: 'dairy' },
  { id: 'parmesan', label: 'Parmesan', group: 'dairy' },
  { id: 'halloumi', label: 'Halloumi', group: 'dairy' },
  { id: 'cream-cheese', label: 'Cream cheese', group: 'dairy' },

  // Pantry
  { id: 'olive-oil', label: 'Olive oil', group: 'pantry' },
  { id: 'peanut-butter', label: 'Peanut butter', group: 'pantry' },
  { id: 'almonds', label: 'Nuts', group: 'pantry' },
  { id: 'honey', label: 'Honey', group: 'pantry' },
  { id: 'soy-sauce', label: 'Soy sauce', group: 'pantry' },
  { id: 'tinned-tomatoes', label: 'Tinned tomatoes', group: 'pantry' },
  { id: 'coconut-milk', label: 'Coconut milk', group: 'pantry' },
  { id: 'curry-paste', label: 'Curry paste', group: 'pantry' },
  { id: 'hummus', label: 'Hummus', group: 'pantry' },
  { id: 'olives', label: 'Olives', group: 'pantry' },
  { id: 'walnuts', label: 'Walnuts', group: 'pantry' },
  { id: 'oats-flour', label: 'Oat flour', group: 'pantry' },
];

export const RECIPES: Recipe[] = [
  // ---------------------------------------------------------------- breakfast
  {
    id: 'yogurt-berry-bowl',
    name: 'Greek yogurt and berry bowl',
    meals: ['breakfast', 'snack'],
    calories: 290,
    macros: { protein: 30, carbs: 32, fat: 4 },
    minutes: 3,
    ingredients: ['greek-yogurt', 'berries', 'honey', 'almonds'],
    steps: [
      'Spoon 250 g of 0% Greek yogurt into a bowl.',
      'Top with a handful of berries and a few chopped nuts.',
      'Finish with a thin drizzle of honey.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'protein-oats',
    name: 'Protein overnight oats',
    meals: ['breakfast'],
    calories: 380,
    macros: { protein: 32, carbs: 45, fat: 8 },
    minutes: 5,
    ingredients: ['oats', 'whey', 'milk', 'berries'],
    steps: [
      'Stir 50 g oats, one scoop of protein and 200 ml milk together.',
      'Refrigerate overnight, or at least two hours.',
      'Top with berries before eating.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'spinach-omelette',
    name: 'Spinach and feta omelette',
    meals: ['breakfast', 'lunch'],
    calories: 320,
    macros: { protein: 26, carbs: 5, fat: 22 },
    minutes: 10,
    ingredients: ['egg', 'spinach', 'feta', 'olive-oil'],
    extras: ['Salt', 'Black pepper'],
    steps: [
      'Beat three eggs with a pinch of salt and pepper.',
      'Wilt a large handful of spinach in a little oil, then pour in the egg.',
      'Scatter over crumbled feta, fold once the base is set.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian', 'keto'],
  },
  {
    id: 'cottage-toast',
    name: 'Cottage cheese toast with tomato',
    meals: ['breakfast', 'snack'],
    calories: 260,
    macros: { protein: 20, carbs: 30, fat: 6 },
    minutes: 5,
    ingredients: ['bread', 'cottage-cheese', 'tomato'],
    extras: ['Black pepper', 'Olive oil to finish'],
    steps: [
      'Toast two slices of wholemeal bread.',
      'Spread thickly with cottage cheese.',
      'Top with sliced tomato, pepper and a few drops of oil.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'banana-pb-shake',
    name: 'Banana peanut butter shake',
    meals: ['breakfast', 'snack'],
    calories: 340,
    macros: { protein: 30, carbs: 34, fat: 10 },
    minutes: 3,
    ingredients: ['banana', 'peanut-butter', 'whey', 'milk'],
    steps: [
      'Blend one banana, a scoop of protein and 250 ml milk.',
      'Add a tablespoon of peanut butter and blend again.',
      'Add ice if you want it thicker.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'shakshuka',
    name: 'Quick one-pan shakshuka',
    meals: ['breakfast', 'lunch'],
    calories: 330,
    macros: { protein: 20, carbs: 22, fat: 18 },
    minutes: 20,
    ingredients: ['egg', 'tomato', 'pepper', 'onion', 'garlic', 'olive-oil'],
    extras: ['Paprika', 'Cumin'],
    steps: [
      'Soften onion, pepper and garlic in oil.',
      'Add chopped tomatoes and spices, simmer ten minutes.',
      'Crack in three eggs, cover, and cook until just set.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'tofu-scramble',
    name: 'Turmeric tofu scramble',
    meals: ['breakfast'],
    calories: 300,
    macros: { protein: 24, carbs: 12, fat: 18 },
    minutes: 12,
    ingredients: ['tofu', 'spinach', 'onion', 'olive-oil'],
    extras: ['Turmeric', 'Salt'],
    steps: [
      'Crumble 200 g firm tofu into a hot, oiled pan.',
      'Add diced onion and turmeric, fry until golden.',
      'Fold through spinach until wilted.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },

  // -------------------------------------------------------------------- lunch
  {
    id: 'tuna-salad',
    name: 'Tuna and white bean salad',
    meals: ['lunch'],
    calories: 380,
    macros: { protein: 38, carbs: 30, fat: 11 },
    minutes: 8,
    ingredients: ['tuna', 'beans', 'salad', 'tomato', 'lemon', 'olive-oil'],
    steps: [
      'Drain a tin of tuna and a tin of beans.',
      'Toss with salad leaves and halved tomatoes.',
      'Dress with lemon juice, oil and plenty of pepper.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'chicken-rice-bowl',
    name: 'Chicken and rice bowl',
    meals: ['lunch', 'dinner'],
    calories: 520,
    macros: { protein: 45, carbs: 55, fat: 12 },
    minutes: 20,
    ingredients: ['chicken', 'rice', 'broccoli', 'soy-sauce', 'garlic'],
    steps: [
      'Cook rice. Meanwhile slice and pan-fry the chicken.',
      'Steam broccoli for four minutes.',
      'Build the bowl and finish with soy sauce and crushed garlic.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'chickpea-feta-salad',
    name: 'Chickpea, cucumber and feta salad',
    meals: ['lunch'],
    calories: 400,
    macros: { protein: 18, carbs: 40, fat: 18 },
    minutes: 8,
    ingredients: ['chickpeas', 'cucumber', 'tomato', 'feta', 'lemon', 'olive-oil'],
    steps: [
      'Rinse a tin of chickpeas and tip into a bowl.',
      'Add diced cucumber and tomato, crumble over feta.',
      'Dress with lemon and oil, season well.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'turkey-wrap',
    name: 'Turkey and avocado wrap',
    meals: ['lunch'],
    calories: 440,
    macros: { protein: 38, carbs: 36, fat: 16 },
    minutes: 7,
    ingredients: ['turkey', 'tortilla', 'avocado', 'salad', 'tomato'],
    steps: [
      'Warm a large tortilla for a few seconds.',
      'Layer sliced turkey, mashed avocado, leaves and tomato.',
      'Roll tightly and cut on the diagonal.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'lentil-soup',
    name: 'Red lentil and tomato soup',
    meals: ['lunch', 'dinner'],
    calories: 330,
    macros: { protein: 19, carbs: 48, fat: 6 },
    minutes: 30,
    ingredients: ['lentils', 'tomato', 'onion', 'garlic', 'olive-oil'],
    extras: ['Cumin', 'Vegetable stock'],
    steps: [
      'Soften onion and garlic in oil with cumin.',
      'Add lentils, chopped tomatoes and a litre of stock.',
      'Simmer 25 minutes, then blend until smooth.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'egg-fried-rice',
    name: 'Egg fried rice with peas',
    meals: ['lunch', 'dinner'],
    calories: 450,
    macros: { protein: 22, carbs: 58, fat: 14 },
    minutes: 12,
    ingredients: ['egg', 'rice', 'onion', 'garlic', 'soy-sauce'],
    extras: ['Frozen peas'],
    steps: [
      'Fry onion and garlic hard in a very hot pan.',
      'Add cold cooked rice and peas, toss for three minutes.',
      'Push aside, scramble two eggs in the gap, then combine.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'caprese-quinoa',
    name: 'Quinoa caprese bowl',
    meals: ['lunch'],
    calories: 420,
    macros: { protein: 20, carbs: 44, fat: 18 },
    minutes: 18,
    ingredients: ['quinoa', 'tomato', 'cheese', 'olive-oil'],
    extras: ['Basil', 'Balsamic vinegar'],
    steps: [
      'Cook quinoa and let it cool slightly.',
      'Fold through torn mozzarella, tomatoes and basil.',
      'Dress with oil and a splash of balsamic.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'prawn-noodle-salad',
    name: 'Cold prawn and cucumber salad',
    meals: ['lunch'],
    calories: 310,
    macros: { protein: 32, carbs: 26, fat: 8 },
    minutes: 12,
    ingredients: ['shrimp', 'cucumber', 'pepper', 'lemon', 'soy-sauce'],
    extras: ['Chilli flakes', 'Sesame oil'],
    steps: [
      'Toss cooked prawns with ribboned cucumber and sliced pepper.',
      'Whisk soy sauce, lemon juice and a little sesame oil.',
      'Dress just before serving so it stays crisp.',
    ],
    diets: ['balanced', 'pescatarian'],
  },

  // ------------------------------------------------------------------- dinner
  {
    id: 'baked-salmon',
    name: 'Baked salmon with greens',
    meals: ['dinner'],
    calories: 480,
    macros: { protein: 40, carbs: 12, fat: 30 },
    minutes: 25,
    ingredients: ['salmon', 'broccoli', 'lemon', 'garlic', 'olive-oil'],
    steps: [
      'Heat the oven to 200 °C.',
      'Bake the salmon with lemon and garlic for 14 minutes.',
      'Serve on lightly steamed broccoli dressed with oil.',
    ],
    diets: ['balanced', 'pescatarian', 'keto'],
  },
  {
    id: 'chicken-traybake',
    name: 'Chicken and vegetable traybake',
    meals: ['dinner'],
    calories: 510,
    macros: { protein: 48, carbs: 40, fat: 16 },
    minutes: 40,
    ingredients: ['chicken', 'potato', 'pepper', 'onion', 'olive-oil', 'garlic'],
    extras: ['Paprika', 'Dried oregano'],
    steps: [
      'Toss chopped potato, pepper and onion in oil and spices.',
      'Roast at 200 °C for 20 minutes.',
      'Add the chicken and roast a further 20 minutes.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'beef-chilli',
    name: 'Lean beef and black bean chilli',
    meals: ['dinner'],
    calories: 470,
    macros: { protein: 42, carbs: 40, fat: 14 },
    minutes: 35,
    ingredients: ['beef', 'beans', 'tomato', 'onion', 'pepper', 'garlic'],
    extras: ['Cumin', 'Chilli powder'],
    steps: [
      'Brown the mince hard, then set aside.',
      'Soften onion, pepper and garlic with the spices.',
      'Return the beef with tomatoes and beans, simmer 20 minutes.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'cod-potatoes',
    name: 'Pan-fried cod with crushed potatoes',
    meals: ['dinner'],
    calories: 430,
    macros: { protein: 40, carbs: 38, fat: 12 },
    minutes: 25,
    ingredients: ['cod', 'potato', 'lemon', 'olive-oil', 'garlic'],
    steps: [
      'Boil potatoes until tender, then crush with oil and garlic.',
      'Fry the cod skin-side down for four minutes.',
      'Flip briefly, then serve with lemon.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'tofu-stirfry',
    name: 'Crispy tofu stir-fry',
    meals: ['dinner'],
    calories: 420,
    macros: { protein: 26, carbs: 40, fat: 18 },
    minutes: 20,
    ingredients: ['tofu', 'broccoli', 'pepper', 'rice', 'soy-sauce', 'garlic'],
    steps: [
      'Press and cube the tofu, fry until golden on all sides.',
      'Add broccoli and pepper, stir-fry three minutes.',
      'Splash in soy sauce and garlic, serve over rice.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'courgette-bolognese',
    name: 'Turkey bolognese with courgette',
    meals: ['dinner'],
    calories: 400,
    macros: { protein: 44, carbs: 22, fat: 15 },
    minutes: 30,
    ingredients: ['turkey', 'courgette', 'tomato', 'onion', 'garlic', 'olive-oil'],
    extras: ['Dried oregano'],
    steps: [
      'Brown turkey mince with onion and garlic.',
      'Add chopped tomatoes and simmer 15 minutes.',
      'Serve over courgette ribbons rather than pasta.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'sweet-potato-curry',
    name: 'Sweet potato and chickpea curry',
    meals: ['dinner'],
    calories: 450,
    macros: { protein: 16, carbs: 66, fat: 14 },
    minutes: 35,
    ingredients: ['sweet-potato', 'chickpeas', 'tomato', 'onion', 'garlic', 'spinach'],
    extras: ['Curry powder', 'Coconut milk'],
    steps: [
      'Fry onion, garlic and curry powder until fragrant.',
      'Add cubed sweet potato, tomatoes and coconut milk.',
      'Simmer 25 minutes, stir in chickpeas and spinach at the end.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'garlic-prawn-pasta',
    name: 'Garlic prawn pasta',
    meals: ['dinner'],
    calories: 520,
    macros: { protein: 38, carbs: 60, fat: 13 },
    minutes: 18,
    ingredients: ['shrimp', 'pasta', 'garlic', 'lemon', 'olive-oil'],
    extras: ['Chilli flakes', 'Parsley'],
    steps: [
      'Cook pasta, reserving a cup of the water.',
      'Fry prawns with garlic and chilli for two minutes.',
      'Toss everything together with lemon and a splash of pasta water.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'stuffed-peppers',
    name: 'Beef-stuffed peppers',
    meals: ['dinner'],
    calories: 390,
    macros: { protein: 34, carbs: 26, fat: 16 },
    minutes: 45,
    ingredients: ['beef', 'pepper', 'rice', 'tomato', 'onion', 'cheese'],
    steps: [
      'Brown the mince with onion and chopped tomato.',
      'Stir through cooked rice and stuff into halved peppers.',
      'Top with cheese and bake at 190 °C for 25 minutes.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'pork-greens',
    name: 'Pork loin with garlic greens',
    meals: ['dinner'],
    calories: 410,
    macros: { protein: 42, carbs: 10, fat: 22 },
    minutes: 22,
    ingredients: ['pork', 'spinach', 'broccoli', 'garlic', 'olive-oil'],
    steps: [
      'Sear the pork four minutes a side, then rest it.',
      'Fry garlic in the same pan, add broccoli and a splash of water.',
      'Wilt in spinach, slice the pork and serve on top.',
    ],
    diets: ['balanced', 'keto'],
  },
  {
    id: 'tempeh-tacos',
    name: 'Tempeh tacos',
    meals: ['dinner', 'lunch'],
    calories: 460,
    macros: { protein: 28, carbs: 48, fat: 18 },
    minutes: 20,
    ingredients: ['tempeh', 'tortilla', 'avocado', 'tomato', 'onion', 'lemon'],
    extras: ['Smoked paprika', 'Coriander'],
    steps: [
      'Crumble and fry tempeh with paprika until crisp.',
      'Mash avocado with lemon and a pinch of salt.',
      'Fill warm tortillas with tempeh, avocado, tomato and onion.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'mushroom-risotto',
    name: 'Mushroom and spinach risotto',
    meals: ['dinner'],
    calories: 480,
    macros: { protein: 16, carbs: 68, fat: 14 },
    minutes: 35,
    ingredients: ['rice', 'mushroom', 'spinach', 'onion', 'garlic', 'cheese'],
    extras: ['Vegetable stock'],
    steps: [
      'Fry mushrooms hard until browned, then set aside.',
      'Soften onion and garlic, add rice, then stock a ladle at a time.',
      'Stir the mushrooms, spinach and cheese through at the end.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'chicken-souvlaki-salad',
    name: 'Chicken souvlaki salad',
    meals: ['dinner', 'lunch'],
    calories: 420,
    macros: { protein: 46, carbs: 16, fat: 19 },
    minutes: 25,
    ingredients: ['chicken', 'cucumber', 'tomato', 'feta', 'lemon', 'olive-oil', 'greek-yogurt'],
    extras: ['Dried oregano'],
    steps: [
      'Marinate diced chicken in lemon, oil and oregano.',
      'Grill or pan-fry until charred at the edges.',
      'Serve over cucumber, tomato and feta with a spoon of yogurt.',
    ],
    diets: ['balanced', 'keto'],
  },

  // -------------------------------------------------------------------- snack
  {
    id: 'cottage-berries',
    name: 'Cottage cheese and berries',
    meals: ['snack'],
    calories: 160,
    macros: { protein: 17, carbs: 16, fat: 3 },
    minutes: 2,
    ingredients: ['cottage-cheese', 'berries'],
    steps: ['Spoon 150 g cottage cheese into a bowl.', 'Top with a handful of berries.'],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'boiled-eggs',
    name: 'Boiled eggs with chilli salt',
    meals: ['snack'],
    calories: 150,
    macros: { protein: 13, carbs: 1, fat: 10 },
    minutes: 9,
    ingredients: ['egg'],
    extras: ['Chilli flakes', 'Flaky salt'],
    steps: [
      'Boil two eggs for seven minutes.',
      'Cool under cold water and peel.',
      'Season with chilli flakes and salt.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian', 'keto'],
  },
  {
    id: 'apple-pb',
    name: 'Banana with peanut butter',
    meals: ['snack'],
    calories: 200,
    macros: { protein: 5, carbs: 29, fat: 8 },
    minutes: 2,
    ingredients: ['banana', 'peanut-butter'],
    steps: ['Slice a banana.', 'Spread a tablespoon of peanut butter over the slices.'],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'yogurt-bark',
    name: 'Frozen yogurt bark',
    meals: ['snack'],
    calories: 180,
    macros: { protein: 16, carbs: 18, fat: 4 },
    minutes: 5,
    ingredients: ['greek-yogurt', 'berries', 'honey'],
    steps: [
      'Spread Greek yogurt thinly on a lined tray.',
      'Scatter berries over and drizzle with honey.',
      'Freeze two hours, then break into shards.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'hummus-veg',
    name: 'Chickpea dip with crudités',
    meals: ['snack'],
    calories: 210,
    macros: { protein: 8, carbs: 22, fat: 10 },
    minutes: 8,
    ingredients: ['chickpeas', 'cucumber', 'pepper', 'lemon', 'olive-oil', 'garlic'],
    steps: [
      'Blend chickpeas with garlic, lemon and oil until smooth.',
      'Loosen with a splash of water.',
      'Serve with cucumber and pepper batons.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'tuna-cucumber-boats',
    name: 'Tuna cucumber boats',
    meals: ['snack'],
    calories: 170,
    macros: { protein: 24, carbs: 5, fat: 6 },
    minutes: 6,
    ingredients: ['tuna', 'cucumber', 'greek-yogurt', 'lemon'],
    steps: [
      'Halve a cucumber lengthways and scoop out the seeds.',
      'Mix tuna with yogurt and lemon juice.',
      'Spoon into the hollow and season.',
    ],
    diets: ['balanced', 'pescatarian', 'keto'],
  },
  {
    id: 'protein-hot-chocolate',
    name: 'Protein hot chocolate',
    meals: ['snack'],
    calories: 190,
    macros: { protein: 26, carbs: 14, fat: 4 },
    minutes: 4,
    ingredients: ['whey', 'milk'],
    extras: ['Cocoa powder'],
    steps: [
      'Warm 250 ml milk with a tablespoon of cocoa.',
      'Take off the heat and let it cool slightly.',
      'Whisk in a scoop of chocolate protein so it does not split.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'avocado-toast-egg',
    name: 'Avocado toast with egg',
    meals: ['snack', 'breakfast'],
    calories: 330,
    macros: { protein: 15, carbs: 28, fat: 19 },
    minutes: 8,
    ingredients: ['bread', 'avocado', 'egg', 'lemon'],
    extras: ['Chilli flakes'],
    steps: [
      'Toast the bread and mash avocado with lemon on top.',
      'Fry or poach an egg.',
      'Slide the egg on and finish with chilli flakes.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },

  // ------------------------------------------------- breakfast (added set)
  {
    id: 'cottage-scramble',
    name: 'Cottage cheese scrambled eggs',
    meals: ['breakfast'],
    calories: 330,
    macros: { protein: 34, carbs: 6, fat: 18 },
    fiber: 1,
    minutes: 8,
    ingredients: ['egg', 'cottage-cheese', 'spinach'],
    extras: ['salt', 'black pepper', 'chives'],
    steps: [
      'Beat 3 eggs with 80 g cottage cheese and a pinch of salt.',
      'Soft-scramble over a low heat, stirring constantly.',
      'Fold through a handful of spinach at the end so it just wilts.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'skyr-apple-bowl',
    name: 'Skyr with apple and walnuts',
    meals: ['breakfast', 'snack'],
    calories: 300,
    macros: { protein: 28, carbs: 30, fat: 8 },
    fiber: 4,
    minutes: 4,
    ingredients: ['greek-yogurt', 'apple', 'walnuts', 'honey'],
    extras: ['cinnamon'],
    steps: [
      'Spoon 250 g skyr or 0% Greek yogurt into a bowl.',
      'Dice an apple and scatter over with a few chopped walnuts.',
      'Dust with cinnamon and add a thin drizzle of honey.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'protein-pancakes',
    name: 'Two-ingredient protein pancakes',
    meals: ['breakfast'],
    calories: 400,
    macros: { protein: 38, carbs: 42, fat: 9 },
    fiber: 5,
    minutes: 12,
    ingredients: ['oats-flour', 'whey', 'egg', 'banana', 'berries'],
    extras: ['baking powder'],
    steps: [
      'Blend 50 g oats, 1 scoop whey, 2 eggs and half a banana into a batter.',
      'Cook small pancakes over a medium heat, about 2 minutes a side.',
      'Stack and top with berries.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'savoury-oats-egg',
    name: 'Savoury oats with a soft egg',
    meals: ['breakfast'],
    calories: 390,
    macros: { protein: 22, carbs: 48, fat: 12 },
    fiber: 7,
    minutes: 12,
    ingredients: ['oats', 'egg', 'spinach', 'parmesan'],
    extras: ['stock', 'black pepper'],
    steps: [
      'Cook 50 g oats in stock rather than milk until thick and creamy.',
      'Stir through a handful of spinach and a little grated parmesan.',
      'Top with a soft-boiled or poached egg.',
    ],
    diets: ['balanced', 'vegetarian'],
  },
  {
    id: 'smoked-salmon-bagel',
    name: 'Smoked salmon and cream cheese on toast',
    meals: ['breakfast', 'lunch'],
    calories: 380,
    macros: { protein: 27, carbs: 34, fat: 15 },
    fiber: 5,
    minutes: 5,
    ingredients: ['bread', 'salmon', 'cream-cheese', 'lemon'],
    extras: ['black pepper', 'dill', 'capers'],
    steps: [
      'Toast two slices of wholemeal bread.',
      'Spread with light cream cheese and lay over smoked salmon.',
      'Squeeze lemon over and finish with black pepper.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'mango-protein-smoothie',
    name: 'Mango protein smoothie',
    meals: ['breakfast', 'snack'],
    calories: 320,
    macros: { protein: 32, carbs: 40, fat: 3 },
    fiber: 4,
    minutes: 3,
    ingredients: ['whey', 'mango', 'greek-yogurt', 'milk'],
    steps: [
      'Blend 1 scoop of protein with 150 g frozen mango.',
      'Add 100 g Greek yogurt and enough milk to loosen.',
      'Blend until smooth.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'egg-white-omelette',
    name: 'Egg white and feta omelette',
    meals: ['breakfast'],
    calories: 250,
    macros: { protein: 32, carbs: 6, fat: 11 },
    fiber: 2,
    minutes: 8,
    ingredients: ['egg', 'feta', 'tomato', 'spinach'],
    extras: ['salt', 'black pepper'],
    steps: [
      'Whisk 6 egg whites with 1 whole egg and a pinch of salt.',
      'Pour into a hot non-stick pan and scatter over tomato and spinach.',
      'Crumble feta on one half, fold and slide out.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'breakfast-burrito',
    name: 'Egg and bean breakfast wrap',
    meals: ['breakfast'],
    calories: 450,
    macros: { protein: 28, carbs: 45, fat: 18 },
    fiber: 9,
    minutes: 10,
    ingredients: ['tortilla', 'egg', 'beans', 'cheese'],
    extras: ['salsa', 'hot sauce'],
    steps: [
      'Scramble 2 eggs and warm a few spoons of black beans.',
      'Pile both onto a tortilla with a little grated cheese.',
      'Add salsa, roll tightly and toast seam-side down for a minute.',
    ],
    diets: ['balanced', 'vegetarian'],
  },
  {
    id: 'overnight-weetabix',
    name: 'Overnight oats with peanut butter',
    meals: ['breakfast'],
    calories: 420,
    macros: { protein: 26, carbs: 48, fat: 14 },
    fiber: 8,
    minutes: 5,
    ingredients: ['oats', 'milk', 'peanut-butter', 'banana', 'whey'],
    steps: [
      'Mix 50 g oats with 200 ml milk and a scoop of protein.',
      'Stir in a tablespoon of peanut butter.',
      'Chill overnight and top with sliced banana in the morning.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'shakshuka-feta',
    name: 'Feta shakshuka',
    meals: ['breakfast', 'lunch'],
    calories: 360,
    macros: { protein: 22, carbs: 22, fat: 21 },
    fiber: 6,
    minutes: 25,
    ingredients: ['egg', 'tinned-tomatoes', 'pepper', 'onion', 'feta'],
    extras: ['cumin', 'paprika', 'olive oil'],
    steps: [
      'Soften onion and pepper, then add tinned tomatoes, cumin and paprika.',
      'Simmer 10 minutes until thick, then make wells and crack in eggs.',
      'Cover and cook until set; crumble feta over to serve.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },

  // ------------------------------------------------------ lunch (added set)
  {
    id: 'chicken-couscous-bowl',
    name: 'Lemon chicken couscous bowl',
    meals: ['lunch', 'dinner'],
    calories: 520,
    macros: { protein: 45, carbs: 55, fat: 12 },
    fiber: 6,
    minutes: 20,
    ingredients: ['chicken', 'couscous', 'cucumber', 'tomato', 'lemon'],
    extras: ['stock', 'olive oil', 'parsley'],
    steps: [
      'Pour boiling stock over 60 g couscous and cover for 5 minutes.',
      'Grill a seasoned chicken breast and slice it.',
      'Fork through the couscous with chopped cucumber, tomato and lemon juice.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'tuna-pasta-salad',
    name: 'Tuna and sweetcorn pasta salad',
    meals: ['lunch'],
    calories: 480,
    macros: { protein: 38, carbs: 58, fat: 9 },
    fiber: 6,
    minutes: 15,
    ingredients: ['tuna', 'pasta', 'sweetcorn', 'greek-yogurt'],
    extras: ['black pepper', 'lemon juice'],
    steps: [
      'Cook 80 g pasta and cool it under cold water.',
      'Mix in a drained tin of tuna, sweetcorn and 2 tbsp Greek yogurt.',
      'Season well with pepper and a squeeze of lemon.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'chicken-caesar-lite',
    name: 'Lighter chicken caesar',
    meals: ['lunch'],
    calories: 420,
    macros: { protein: 45, carbs: 16, fat: 20 },
    fiber: 4,
    minutes: 15,
    ingredients: ['chicken', 'salad', 'parmesan', 'greek-yogurt'],
    extras: ['garlic', 'anchovy', 'lemon', 'black pepper'],
    steps: [
      'Whisk Greek yogurt with lemon, garlic and a little grated parmesan.',
      'Toss through crisp lettuce.',
      'Top with sliced grilled chicken and more parmesan.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'halloumi-quinoa-salad',
    name: 'Halloumi and quinoa salad',
    meals: ['lunch'],
    calories: 520,
    macros: { protein: 28, carbs: 45, fat: 26 },
    fiber: 7,
    minutes: 18,
    ingredients: ['halloumi', 'quinoa', 'pepper', 'courgette', 'lemon'],
    extras: ['olive oil', 'mint'],
    steps: [
      'Cook 60 g quinoa and let it cool slightly.',
      'Griddle sliced halloumi, pepper and courgette until charred.',
      'Toss everything with lemon juice, olive oil and torn mint.',
    ],
    diets: ['balanced', 'vegetarian'],
  },
  {
    id: 'sardine-toast',
    name: 'Sardines on sourdough',
    meals: ['lunch'],
    calories: 400,
    macros: { protein: 30, carbs: 32, fat: 17 },
    fiber: 5,
    minutes: 6,
    ingredients: ['sardines', 'bread', 'tomato', 'lemon'],
    extras: ['chilli flakes', 'olive oil'],
    steps: [
      'Toast two thick slices of bread and rub with a cut tomato.',
      'Lay over a tin of drained sardines and break them up roughly.',
      'Finish with lemon, chilli flakes and a little olive oil.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'chicken-pitta-hummus',
    name: 'Chicken and hummus pitta',
    meals: ['lunch'],
    calories: 480,
    macros: { protein: 42, carbs: 48, fat: 13 },
    fiber: 8,
    minutes: 10,
    ingredients: ['chicken', 'pitta', 'hummus', 'salad', 'cucumber'],
    extras: ['paprika', 'lemon'],
    steps: [
      'Warm a wholemeal pitta and split it open.',
      'Spread the inside with hummus.',
      'Stuff with sliced chicken, salad leaves and cucumber.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'edamame-noodle-bowl',
    name: 'Edamame and sesame noodle bowl',
    meals: ['lunch'],
    calories: 460,
    macros: { protein: 25, carbs: 60, fat: 13 },
    fiber: 9,
    minutes: 15,
    ingredients: ['noodles', 'edamame', 'carrot', 'cabbage', 'soy-sauce'],
    extras: ['sesame oil', 'rice vinegar', 'sesame seeds'],
    steps: [
      'Cook noodles and rinse under cold water.',
      'Toss with shelled edamame, shredded carrot and cabbage.',
      'Dress with soy sauce, a little sesame oil and vinegar.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'lentil-feta-salad',
    name: 'Lentil, feta and tomato salad',
    meals: ['lunch'],
    calories: 430,
    macros: { protein: 24, carbs: 42, fat: 18 },
    fiber: 12,
    minutes: 10,
    ingredients: ['lentils', 'feta', 'tomato', 'cucumber', 'olives'],
    extras: ['olive oil', 'red wine vinegar', 'oregano'],
    steps: [
      'Drain a tin of lentils and tip into a bowl.',
      'Add chopped tomato, cucumber and olives.',
      'Crumble feta over and dress with oil, vinegar and oregano.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'turkey-rice-bowl',
    name: 'Turkey and black bean rice bowl',
    meals: ['lunch', 'dinner'],
    calories: 550,
    macros: { protein: 45, carbs: 62, fat: 12 },
    fiber: 11,
    minutes: 20,
    ingredients: ['turkey', 'rice', 'beans', 'pepper', 'avocado'],
    extras: ['cumin', 'paprika', 'lime'],
    steps: [
      'Brown turkey mince with cumin and paprika.',
      'Stir in black beans and diced pepper until hot through.',
      'Serve over rice with sliced avocado and lime.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'cottage-cheese-jacket',
    name: 'Jacket potato with cottage cheese',
    meals: ['lunch'],
    calories: 400,
    macros: { protein: 26, carbs: 55, fat: 8 },
    fiber: 7,
    minutes: 55,
    ingredients: ['potato', 'cottage-cheese', 'spinach'],
    extras: ['black pepper', 'chives'],
    steps: [
      'Bake a large potato until the skin is crisp.',
      'Split and fill with cottage cheese.',
      'Wilt spinach through the hot potato and season well.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'chicken-soup-noodle',
    name: 'Chicken noodle soup',
    meals: ['lunch'],
    calories: 380,
    macros: { protein: 38, carbs: 40, fat: 6 },
    fiber: 5,
    minutes: 25,
    ingredients: ['chicken', 'noodles', 'carrot', 'onion', 'garlic'],
    extras: ['stock', 'ginger', 'black pepper'],
    steps: [
      'Simmer chicken with stock, carrot, onion, garlic and ginger.',
      'Shred the chicken and return it to the pot.',
      'Add noodles for the last few minutes.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'egg-salad-sandwich',
    name: 'Yogurt egg salad sandwich',
    meals: ['lunch'],
    calories: 420,
    macros: { protein: 28, carbs: 36, fat: 18 },
    fiber: 6,
    minutes: 12,
    ingredients: ['egg', 'bread', 'greek-yogurt', 'salad'],
    extras: ['mustard', 'chives', 'black pepper'],
    steps: [
      'Hard-boil 4 eggs, cool and chop roughly.',
      'Mix with Greek yogurt and a little mustard instead of mayonnaise.',
      'Pile onto wholemeal bread with salad leaves.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'prawn-avocado-salad',
    name: 'Prawn and avocado salad',
    meals: ['lunch'],
    calories: 380,
    macros: { protein: 32, carbs: 14, fat: 22 },
    fiber: 8,
    minutes: 10,
    ingredients: ['shrimp', 'avocado', 'salad', 'cucumber', 'lemon'],
    extras: ['olive oil', 'black pepper'],
    steps: [
      'Pile salad leaves and cucumber into a bowl.',
      'Add cooked prawns and sliced avocado.',
      'Dress with lemon juice, a little olive oil and plenty of pepper.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'chickpea-tuna-mash',
    name: 'Smashed chickpea and tuna wrap',
    meals: ['lunch'],
    calories: 470,
    macros: { protein: 36, carbs: 50, fat: 13 },
    fiber: 11,
    minutes: 8,
    ingredients: ['chickpeas', 'tuna', 'tortilla', 'greek-yogurt', 'salad'],
    extras: ['lemon', 'black pepper'],
    steps: [
      'Roughly mash a drained tin of chickpeas with a fork.',
      'Stir in tuna, Greek yogurt and lemon juice.',
      'Spread over a wrap, add salad leaves and roll up.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'kale-chicken-caesar-quinoa',
    name: 'Kale, chicken and quinoa bowl',
    meals: ['lunch', 'dinner'],
    calories: 510,
    macros: { protein: 44, carbs: 45, fat: 16 },
    fiber: 9,
    minutes: 22,
    ingredients: ['chicken', 'quinoa', 'kale', 'almonds', 'lemon'],
    extras: ['olive oil', 'garlic'],
    steps: [
      'Massage shredded kale with lemon juice and a little olive oil.',
      'Fold through cooked quinoa and sliced grilled chicken.',
      'Scatter over toasted flaked almonds.',
    ],
    diets: ['balanced'],
  },

  // ----------------------------------------------------- dinner (added set)
  {
    id: 'chicken-fajitas',
    name: 'Chicken fajitas',
    meals: ['dinner'],
    calories: 540,
    macros: { protein: 46, carbs: 52, fat: 14 },
    fiber: 8,
    minutes: 25,
    ingredients: ['chicken', 'tortilla', 'pepper', 'onion', 'greek-yogurt'],
    extras: ['paprika', 'cumin', 'lime', 'olive oil'],
    steps: [
      'Toss chicken strips with paprika, cumin and a little oil.',
      'Fry hot with sliced peppers and onion until charred at the edges.',
      'Serve in warm tortillas with Greek yogurt instead of sour cream.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'salmon-teriyaki-rice',
    name: 'Teriyaki salmon with rice',
    meals: ['dinner'],
    calories: 600,
    macros: { protein: 42, carbs: 60, fat: 19 },
    fiber: 5,
    minutes: 22,
    ingredients: ['salmon', 'rice', 'broccoli', 'soy-sauce', 'honey'],
    extras: ['ginger', 'garlic', 'sesame seeds'],
    steps: [
      'Mix soy sauce, honey, grated ginger and garlic into a glaze.',
      'Roast a salmon fillet for 12 minutes, brushing with the glaze.',
      'Serve on rice with steamed broccoli and sesame seeds.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'turkey-meatballs',
    name: 'Turkey meatballs in tomato sauce',
    meals: ['dinner'],
    calories: 520,
    macros: { protein: 48, carbs: 45, fat: 16 },
    fiber: 8,
    minutes: 35,
    ingredients: ['turkey', 'tinned-tomatoes', 'pasta', 'garlic', 'onion'],
    extras: ['oregano', 'olive oil', 'black pepper'],
    steps: [
      'Roll turkey mince into meatballs and brown them all over.',
      'Simmer in tinned tomatoes with garlic, onion and oregano for 20 minutes.',
      'Serve over pasta.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'chicken-katsu-lite',
    name: 'Baked chicken katsu curry',
    meals: ['dinner'],
    calories: 620,
    macros: { protein: 48, carbs: 68, fat: 17 },
    fiber: 7,
    minutes: 35,
    ingredients: ['chicken', 'rice', 'curry-paste', 'carrot', 'onion'],
    extras: ['breadcrumbs', 'stock', 'egg'],
    steps: [
      'Coat chicken in breadcrumbs and bake until crisp rather than frying.',
      'Simmer curry paste with onion, carrot and stock, then blend smooth.',
      'Slice the chicken over rice and pour the sauce round it.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'cod-tomato-olives',
    name: 'Baked cod with tomatoes and olives',
    meals: ['dinner'],
    calories: 420,
    macros: { protein: 40, carbs: 22, fat: 19 },
    fiber: 6,
    minutes: 28,
    ingredients: ['cod', 'tomato', 'olives', 'potato', 'garlic'],
    extras: ['olive oil', 'oregano', 'lemon'],
    steps: [
      'Roast halved new potatoes with garlic for 20 minutes.',
      'Add cod fillets, tomatoes and olives to the tray.',
      'Return for 12 minutes until the fish flakes.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'beef-stir-fry',
    name: 'Beef and green bean stir fry',
    meals: ['dinner'],
    calories: 560,
    macros: { protein: 45, carbs: 52, fat: 18 },
    fiber: 7,
    minutes: 20,
    ingredients: ['beef', 'green-beans', 'rice', 'garlic', 'soy-sauce'],
    extras: ['ginger', 'chilli', 'sesame oil'],
    steps: [
      'Sear strips of beef hard and fast, then set aside.',
      'Stir-fry green beans with garlic, ginger and chilli.',
      'Return the beef, splash in soy sauce and serve over rice.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'aubergine-parmigiana-lite',
    name: 'Lighter aubergine parmigiana',
    meals: ['dinner'],
    calories: 430,
    macros: { protein: 26, carbs: 28, fat: 24 },
    fiber: 9,
    minutes: 45,
    ingredients: ['aubergine', 'tinned-tomatoes', 'mozzarella', 'parmesan', 'garlic'],
    extras: ['basil', 'olive oil'],
    steps: [
      'Griddle aubergine slices dry rather than frying them in oil.',
      'Layer with a garlicky tomato sauce, mozzarella and parmesan.',
      'Bake 25 minutes until bubbling.',
    ],
    diets: ['balanced', 'vegetarian'],
  },
  {
    id: 'thai-green-chicken',
    name: 'Thai green chicken curry',
    meals: ['dinner'],
    calories: 580,
    macros: { protein: 42, carbs: 52, fat: 22 },
    fiber: 6,
    minutes: 25,
    ingredients: ['chicken', 'coconut-milk', 'curry-paste', 'green-beans', 'rice'],
    extras: ['fish sauce', 'lime', 'basil'],
    steps: [
      'Fry curry paste until fragrant, then add light coconut milk.',
      'Simmer chicken and green beans in the sauce for 12 minutes.',
      'Finish with lime and basil; serve with rice.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'lamb-kofta-couscous',
    name: 'Lamb kofta with couscous',
    meals: ['dinner'],
    calories: 620,
    macros: { protein: 42, carbs: 50, fat: 26 },
    fiber: 6,
    minutes: 30,
    ingredients: ['lamb', 'couscous', 'greek-yogurt', 'cucumber', 'onion'],
    extras: ['cumin', 'coriander', 'mint', 'garlic'],
    steps: [
      'Mix lamb mince with grated onion, cumin and coriander; shape onto skewers.',
      'Grill 10 minutes, turning once.',
      'Serve on couscous with a yogurt, cucumber and mint sauce.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'tofu-peanut-noodles',
    name: 'Peanut tofu noodles',
    meals: ['dinner'],
    calories: 560,
    macros: { protein: 30, carbs: 58, fat: 24 },
    fiber: 9,
    minutes: 20,
    ingredients: ['tofu', 'noodles', 'peanut-butter', 'cabbage', 'carrot'],
    extras: ['soy sauce', 'lime', 'chilli', 'garlic'],
    steps: [
      'Press and cube tofu, then bake or pan-fry until golden.',
      'Whisk peanut butter with soy, lime, garlic and hot water into a sauce.',
      'Toss through noodles, shredded cabbage and carrot with the tofu.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan'],
  },
  {
    id: 'chicken-butternut-traybake',
    name: 'Chicken and butternut traybake',
    meals: ['dinner'],
    calories: 500,
    macros: { protein: 44, carbs: 40, fat: 17 },
    fiber: 8,
    minutes: 40,
    ingredients: ['chicken', 'butternut', 'onion', 'pepper', 'olive-oil'],
    extras: ['paprika', 'thyme', 'garlic'],
    steps: [
      'Toss cubed butternut, onion and pepper with oil and paprika.',
      'Roast 20 minutes, then nestle in chicken thighs.',
      'Roast a further 20 minutes until everything is caramelised.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'cauliflower-dhal',
    name: 'Cauliflower and lentil dhal',
    meals: ['dinner'],
    calories: 440,
    macros: { protein: 22, carbs: 60, fat: 12 },
    fiber: 16,
    minutes: 35,
    ingredients: ['lentils', 'cauliflower', 'onion', 'garlic', 'coconut-milk'],
    extras: ['curry powder', 'ginger', 'stock', 'coriander'],
    steps: [
      'Soften onion, garlic and ginger with curry powder.',
      'Add red lentils, cauliflower florets, stock and light coconut milk.',
      'Simmer 25 minutes until the lentils collapse.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'pork-apple-greens',
    name: 'Pork steaks with apple and greens',
    meals: ['dinner'],
    calories: 480,
    macros: { protein: 44, carbs: 28, fat: 21 },
    fiber: 6,
    minutes: 25,
    ingredients: ['pork', 'apple', 'cabbage', 'potato'],
    extras: ['mustard', 'stock', 'butter'],
    steps: [
      'Pan-fry pork steaks and rest them.',
      'Cook sliced apple and shredded cabbage in the same pan with a splash of stock.',
      'Stir mustard through and serve with boiled potatoes.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'prawn-tomato-linguine',
    name: 'Prawn and tomato linguine',
    meals: ['dinner'],
    calories: 540,
    macros: { protein: 38, carbs: 65, fat: 13 },
    fiber: 7,
    minutes: 20,
    ingredients: ['shrimp', 'pasta', 'tinned-tomatoes', 'garlic', 'lemon'],
    extras: ['chilli flakes', 'olive oil', 'parsley'],
    steps: [
      'Cook pasta until just short of done.',
      'Fry garlic and chilli, add tomatoes and simmer 8 minutes.',
      'Stir in prawns and the drained pasta; finish with lemon and parsley.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'stuffed-sweet-potato',
    name: 'Stuffed sweet potato with chilli beans',
    meals: ['dinner'],
    calories: 470,
    macros: { protein: 22, carbs: 72, fat: 10 },
    fiber: 16,
    minutes: 50,
    ingredients: ['sweet-potato', 'beans', 'tinned-tomatoes', 'cheese', 'onion'],
    extras: ['cumin', 'chilli powder'],
    steps: [
      'Bake sweet potatoes until soft.',
      'Simmer black beans with tomatoes, onion, cumin and chilli.',
      'Split the potatoes, spoon the beans in and top with a little cheese.',
    ],
    diets: ['balanced', 'vegetarian'],
  },
  {
    id: 'chicken-broccoli-pasta-bake',
    name: 'Chicken and broccoli pasta bake',
    meals: ['dinner'],
    calories: 590,
    macros: { protein: 48, carbs: 62, fat: 16 },
    fiber: 8,
    minutes: 40,
    ingredients: ['chicken', 'pasta', 'broccoli', 'cottage-cheese', 'cheese'],
    extras: ['garlic', 'mustard', 'black pepper'],
    steps: [
      'Blend cottage cheese with garlic and mustard into a high-protein sauce.',
      'Fold through cooked pasta, chicken and blanched broccoli.',
      'Top with grated cheese and bake 20 minutes.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'tempeh-tray-roast',
    name: 'Tempeh and root vegetable roast',
    meals: ['dinner'],
    calories: 490,
    macros: { protein: 28, carbs: 48, fat: 20 },
    fiber: 12,
    minutes: 40,
    ingredients: ['tempeh', 'carrot', 'butternut', 'onion', 'olive-oil'],
    extras: ['soy sauce', 'maple syrup', 'smoked paprika'],
    steps: [
      'Toss tempeh in soy sauce, maple and smoked paprika.',
      'Roast with carrot, butternut and onion for 30 minutes.',
      'Turn once so everything caramelises evenly.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'cod-green-curry',
    name: 'Cod and pea curry',
    meals: ['dinner'],
    calories: 450,
    macros: { protein: 38, carbs: 42, fat: 13 },
    fiber: 8,
    minutes: 25,
    ingredients: ['cod', 'peas', 'curry-paste', 'coconut-milk', 'rice'],
    extras: ['lime', 'coriander'],
    steps: [
      'Fry curry paste, then add light coconut milk and bring to a simmer.',
      'Poach chunks of cod with peas for 8 minutes.',
      'Finish with lime and coriander; serve with rice.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'mushroom-chicken-stroganoff',
    name: 'Chicken and mushroom stroganoff',
    meals: ['dinner'],
    calories: 520,
    macros: { protein: 46, carbs: 48, fat: 14 },
    fiber: 5,
    minutes: 25,
    ingredients: ['chicken', 'mushroom', 'greek-yogurt', 'rice', 'onion'],
    extras: ['paprika', 'mustard', 'stock'],
    steps: [
      'Brown chicken strips, then soften onion and mushrooms in the pan.',
      'Add paprika, mustard and a little stock and reduce.',
      'Take off the heat and stir in Greek yogurt so it does not split.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'halloumi-chickpea-traybake',
    name: 'Halloumi and chickpea traybake',
    meals: ['dinner'],
    calories: 540,
    macros: { protein: 30, carbs: 44, fat: 27 },
    fiber: 11,
    minutes: 35,
    ingredients: ['halloumi', 'chickpeas', 'pepper', 'courgette', 'tomato'],
    extras: ['olive oil', 'oregano', 'lemon'],
    steps: [
      'Roast chickpeas, peppers, courgette and tomatoes with oil and oregano.',
      'Add cubed halloumi for the last 10 minutes.',
      'Squeeze lemon over before serving.',
    ],
    diets: ['balanced', 'vegetarian'],
  },

  // ------------------------------------------------ snacks & extras (added)
  {
    id: 'cottage-cheese-crackers',
    name: 'Cottage cheese with oatcakes',
    meals: ['snack'],
    calories: 240,
    macros: { protein: 20, carbs: 22, fat: 8 },
    fiber: 3,
    minutes: 2,
    ingredients: ['cottage-cheese', 'tomato'],
    extras: ['oatcakes', 'black pepper'],
    steps: [
      'Spoon cottage cheese onto three oatcakes.',
      'Top with sliced tomato and plenty of black pepper.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'edamame-snack',
    name: 'Salted edamame',
    meals: ['snack'],
    calories: 130,
    macros: { protein: 12, carbs: 9, fat: 5 },
    fiber: 5,
    minutes: 5,
    ingredients: ['edamame'],
    extras: ['sea salt', 'chilli flakes'],
    steps: [
      'Boil or steam frozen edamame pods for 4 minutes.',
      'Drain and toss with sea salt and chilli flakes.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'hummus-veg-sticks',
    name: 'Hummus with vegetable sticks',
    meals: ['snack'],
    calories: 210,
    macros: { protein: 8, carbs: 20, fat: 12 },
    fiber: 7,
    minutes: 4,
    ingredients: ['hummus', 'carrot', 'pepper', 'cucumber'],
    steps: [
      'Cut carrot, pepper and cucumber into sticks.',
      'Serve with a 60 g portion of hummus.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'apple-walnut-yogurt',
    name: 'Apple, walnut and yogurt pot',
    meals: ['snack'],
    calories: 250,
    macros: { protein: 18, carbs: 24, fat: 10 },
    fiber: 4,
    minutes: 3,
    ingredients: ['greek-yogurt', 'apple', 'walnuts'],
    extras: ['cinnamon'],
    steps: [
      'Layer Greek yogurt with diced apple.',
      'Top with a few crushed walnuts and cinnamon.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'egg-avocado-toast',
    name: 'Egg and avocado toast',
    meals: ['snack', 'breakfast'],
    calories: 380,
    macros: { protein: 20, carbs: 30, fat: 21 },
    fiber: 9,
    minutes: 8,
    ingredients: ['egg', 'avocado', 'bread', 'lemon'],
    extras: ['chilli flakes', 'salt'],
    steps: [
      'Mash half an avocado with lemon and salt onto toast.',
      'Top with two poached or boiled eggs.',
      'Finish with chilli flakes.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'orange-almonds',
    name: 'Orange and almonds',
    meals: ['snack'],
    calories: 230,
    macros: { protein: 7, carbs: 20, fat: 15 },
    fiber: 6,
    minutes: 1,
    ingredients: ['orange', 'almonds'],
    steps: ['Eat an orange with a 25 g handful of almonds.'],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'protein-mug-cake',
    name: 'Protein mug cake',
    meals: ['snack'],
    calories: 280,
    macros: { protein: 30, carbs: 26, fat: 7 },
    fiber: 4,
    minutes: 5,
    ingredients: ['whey', 'oats-flour', 'egg', 'milk'],
    extras: ['cocoa powder', 'baking powder'],
    steps: [
      'Mix 1 scoop protein, 20 g oat flour, 1 egg and a splash of milk in a mug.',
      'Add cocoa and a pinch of baking powder.',
      'Microwave 60–80 seconds — stop while it still looks slightly wet.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },

  // ------------------------------------------- batch cooking & one-pan (added)
  {
    id: 'chilli-batch',
    name: 'Batch beef and bean chilli',
    meals: ['dinner', 'lunch'],
    calories: 480,
    macros: { protein: 40, carbs: 44, fat: 15 },
    fiber: 14,
    minutes: 45,
    ingredients: ['beef', 'beans', 'tinned-tomatoes', 'pepper', 'onion'],
    extras: ['cumin', 'chilli powder', 'stock', 'dark chocolate'],
    steps: [
      'Brown 500 g lean beef mince with onion and pepper.',
      'Add tinned tomatoes, black beans, cumin and chilli; simmer 30 minutes.',
      'A square of dark chocolate at the end rounds it out. Makes four portions.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'chicken-meal-prep',
    name: 'Meal-prep chicken, rice and broccoli',
    meals: ['lunch', 'dinner'],
    calories: 520,
    macros: { protein: 48, carbs: 58, fat: 9 },
    fiber: 6,
    minutes: 35,
    ingredients: ['chicken', 'rice', 'broccoli', 'soy-sauce'],
    extras: ['garlic', 'paprika', 'olive oil'],
    steps: [
      'Bake four seasoned chicken breasts together for 22 minutes.',
      'Cook a large pan of rice and steam broccoli.',
      'Divide into four containers; they keep three days in the fridge.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'lentil-bolognese',
    name: 'Lentil bolognese',
    meals: ['dinner'],
    calories: 470,
    macros: { protein: 24, carbs: 72, fat: 9 },
    fiber: 17,
    minutes: 40,
    ingredients: ['lentils', 'tinned-tomatoes', 'pasta', 'carrot', 'onion'],
    extras: ['garlic', 'oregano', 'stock', 'olive oil'],
    steps: [
      'Soften finely diced carrot, onion and garlic.',
      'Add lentils, tinned tomatoes, stock and oregano; simmer 25 minutes.',
      'Serve over pasta.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'minestrone-batch',
    name: 'Bean and vegetable minestrone',
    meals: ['lunch', 'dinner'],
    calories: 330,
    macros: { protein: 16, carbs: 52, fat: 6 },
    fiber: 14,
    minutes: 35,
    ingredients: ['beans', 'tinned-tomatoes', 'carrot', 'cabbage', 'pasta'],
    extras: ['stock', 'garlic', 'parmesan rind', 'olive oil'],
    steps: [
      'Soften carrot, onion and garlic, then add tomatoes and stock.',
      'Simmer with beans and shredded cabbage for 20 minutes.',
      'Add small pasta for the last 8 minutes.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'roast-veg-feta-quinoa',
    name: 'Roast vegetable and feta quinoa',
    meals: ['lunch', 'dinner'],
    calories: 470,
    macros: { protein: 20, carbs: 52, fat: 20 },
    fiber: 11,
    minutes: 40,
    ingredients: ['quinoa', 'aubergine', 'courgette', 'pepper', 'feta'],
    extras: ['olive oil', 'oregano', 'lemon'],
    steps: [
      'Roast chunks of aubergine, courgette and pepper for 30 minutes.',
      'Fold through cooked quinoa while still warm.',
      'Crumble feta over and dress with lemon.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'salmon-traybake-greens',
    name: 'Salmon traybake with greens',
    meals: ['dinner'],
    calories: 540,
    macros: { protein: 40, carbs: 38, fat: 25 },
    fiber: 8,
    minutes: 30,
    ingredients: ['salmon', 'potato', 'green-beans', 'lemon', 'olive-oil'],
    extras: ['garlic', 'dill', 'black pepper'],
    steps: [
      'Roast halved new potatoes for 20 minutes.',
      'Add salmon fillets and green beans to the tray with lemon and garlic.',
      'Roast a further 12 minutes.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'tofu-katsu',
    name: 'Baked tofu katsu',
    meals: ['dinner'],
    calories: 540,
    macros: { protein: 28, carbs: 66, fat: 18 },
    fiber: 8,
    minutes: 35,
    ingredients: ['tofu', 'rice', 'curry-paste', 'carrot', 'onion'],
    extras: ['breadcrumbs', 'stock', 'soy sauce'],
    steps: [
      'Press tofu, slice thickly, coat in breadcrumbs and bake until crisp.',
      'Simmer curry paste with onion, carrot and stock; blend smooth.',
      'Serve over rice with the sauce poured round.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan'],
  },
  {
    id: 'chicken-greek-salad',
    name: 'Greek chicken salad',
    meals: ['lunch', 'dinner'],
    calories: 460,
    macros: { protein: 44, carbs: 18, fat: 24 },
    fiber: 5,
    minutes: 15,
    ingredients: ['chicken', 'cucumber', 'tomato', 'olives', 'feta'],
    extras: ['red onion', 'oregano', 'olive oil', 'red wine vinegar'],
    steps: [
      'Chop cucumber, tomato and red onion into a bowl.',
      'Add olives, cubed feta and sliced grilled chicken.',
      'Dress with oil, vinegar and oregano.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'egg-fried-cauli-rice',
    name: 'Egg fried cauliflower rice',
    meals: ['dinner', 'lunch'],
    calories: 320,
    macros: { protein: 26, carbs: 20, fat: 16 },
    fiber: 8,
    minutes: 15,
    ingredients: ['cauliflower', 'egg', 'peas', 'soy-sauce', 'garlic'],
    extras: ['sesame oil', 'spring onion', 'ginger'],
    steps: [
      'Blitz cauliflower into rice-sized pieces and dry-fry to drive off water.',
      'Push aside, scramble eggs in the pan, then combine with peas.',
      'Season with soy sauce, garlic and a little sesame oil.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'turkey-lettuce-wraps',
    name: 'Turkey san choy bau',
    meals: ['dinner', 'lunch'],
    calories: 380,
    macros: { protein: 42, carbs: 18, fat: 15 },
    fiber: 5,
    minutes: 20,
    ingredients: ['turkey', 'salad', 'carrot', 'mushroom', 'soy-sauce'],
    extras: ['ginger', 'garlic', 'sesame oil', 'lime'],
    steps: [
      'Fry turkey mince hard with garlic, ginger and chopped mushroom.',
      'Season with soy sauce and a little sesame oil.',
      'Spoon into crisp lettuce cups with shredded carrot.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'baked-oats-berry',
    name: 'Baked protein oats',
    meals: ['breakfast'],
    calories: 420,
    macros: { protein: 30, carbs: 52, fat: 10 },
    fiber: 8,
    minutes: 30,
    ingredients: ['oats', 'whey', 'egg', 'berries', 'milk'],
    extras: ['baking powder', 'cinnamon'],
    steps: [
      'Blend oats, protein, an egg, milk and baking powder into a batter.',
      'Pour into a small dish and press berries into the top.',
      'Bake at 180 °C for 22 minutes.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
  {
    id: 'chickpea-curry-batch',
    name: 'Batch chickpea and spinach curry',
    meals: ['dinner', 'lunch'],
    calories: 450,
    macros: { protein: 18, carbs: 60, fat: 15 },
    fiber: 14,
    minutes: 30,
    ingredients: ['chickpeas', 'spinach', 'tinned-tomatoes', 'coconut-milk', 'rice'],
    extras: ['curry powder', 'garlic', 'ginger', 'onion'],
    steps: [
      'Fry onion, garlic, ginger and curry powder until fragrant.',
      'Add chickpeas, tomatoes and light coconut milk; simmer 20 minutes.',
      'Wilt in spinach at the end. Serve with rice; makes three portions.',
    ],
    diets: ['balanced', 'vegetarian', 'vegan', 'pescatarian'],
  },
  {
    id: 'cod-cauliflower-mash',
    name: 'Cod with cauliflower mash',
    meals: ['dinner'],
    calories: 380,
    macros: { protein: 42, carbs: 22, fat: 14 },
    fiber: 7,
    minutes: 25,
    ingredients: ['cod', 'cauliflower', 'green-beans', 'garlic'],
    extras: ['butter', 'lemon', 'black pepper'],
    steps: [
      'Boil cauliflower until very soft, then blend with garlic and a knob of butter.',
      'Pan-fry or bake cod fillets for 10 minutes.',
      'Serve on the mash with green beans and lemon.',
    ],
    diets: ['balanced', 'pescatarian'],
  },
  {
    id: 'beef-burger-lean',
    name: 'Lean beef burger',
    meals: ['dinner'],
    calories: 520,
    macros: { protein: 44, carbs: 40, fat: 20 },
    fiber: 6,
    minutes: 20,
    ingredients: ['beef', 'bread', 'salad', 'tomato', 'onion'],
    extras: ['mustard', 'black pepper'],
    steps: [
      'Shape 5% beef mince into patties, season hard and griddle 4 minutes a side.',
      'Toast a wholemeal roll.',
      'Build with mustard, lettuce, tomato and raw onion.',
    ],
    diets: ['balanced'],
  },
  {
    id: 'pea-mint-soup',
    name: 'Pea, mint and yogurt soup',
    meals: ['lunch'],
    calories: 260,
    macros: { protein: 18, carbs: 32, fat: 6 },
    fiber: 11,
    minutes: 15,
    ingredients: ['peas', 'greek-yogurt', 'onion', 'garlic'],
    extras: ['stock', 'mint', 'black pepper'],
    steps: [
      'Soften onion and garlic, add stock and bring to the boil.',
      'Add frozen peas and cook 4 minutes, then blend with fresh mint.',
      'Stir Greek yogurt through off the heat.',
    ],
    diets: ['balanced', 'vegetarian', 'pescatarian'],
  },
];
